### ISSUE TITLE
Do we need another build system?

### ISSUE THREAD

**Issue by DamonOehlman** [DamonOehlman/smoke#1]
Do we really need another build system?  Don't he have the tools we need to do the job already?

**Comment by DamonOehlman** [comment]
Personally, I don't.  But if other people do, then I'll just stick with mashing things into [Interleave](/DamonOehlman/interleave) to meet my own requirements.

**Comment by paulirish** [comment]
I think Grunt captures a good amount of community energy and covers most of the scope for what you'd like to do here

**Comment by DamonOehlman** [comment]
That was my thought too Paul, and was very happy to use what someone else's hard work.  That said I forked the repo and trying to add a couple of features around the node streams stuff.  Started off great - documentation was good, code was easy to work with, but it all kind of fell apart once I wanted to integrate with [Rigger](/DamonOehlman/rigger) which is able to do remote includes and thus works asynchronously.  Under the hood Grunt uses synchronous node functions (like [readFileSync](http://nodejs.org/docs/latest/api/fs.html#fs_fs_readfilesync_filename_encoding), [writeFileSync](http://nodejs.org/docs/latest/api/fs.html#fs_fs_writefilesync_filename_data_encoding)) and would have written the output file by the time by remote include would have resolved :(

While it would be possible to rewrite the core parts of Grunt to work with the asynchronous equivalents, it's definitely something that has some impact to the rest of the project.  If @cowboy was keen, then I'd be happy to do it.

Thanks for your feedback :)

**Comment by paulirish** [comment]
Hmmm yeah! Sounds lovely to me if grunt used the async file I/O methods.. 

Ben?

**Comment by cowboy** [comment]
@DamonOehlman I took a brief look at both Rigger and don't see why it wouldn't work as part of a grunt task. Since grunt tasks can be made async using the `this.async` method, it would be easy to just do all the async fetching, writing, etc inside  the task, and then just tell grunt when everything is done.

You can use the build-in grunt file I/O methods, of course, but if you need to use custom I/O methods, well.. it's all just Node.js JavaScript. You could very easily write your own or use Rigger's built-in I/O. Or maybe we can extend grunt's I/O methods to be async.

I only took a brief look at Rigger, but if Rigger allowed you to process non-file streams or just strings of source code, you'd have a lot of flexibility in how it was used. For example, even though you can run UglifyJS on the command-line to read an input file from and write an output file to the filesystem, you can also `require` it and use it to just parse an unminified string and return a minified string, without any of the filesystem I/O. This allows you to use your own I/O, which is how grunt's `min` task uses UglifyJS.

In my brief look at Rigger, I only saw the ability to parse files read from the filesystem, whose result was output to the filesystem, but I may have missed something. If Rigger made the file I/O optional, you could use grunt's API to read files, then process them with Rigger, then use grunt's API to write output files. Can Rigger be used like this?

Either way, Rigger sounds really useful. I'd imagine a lot of people could make good use of a `rig` grunt task. Would you be interested in create a `rig` grunt task, and showing me where the pain points are?

Thanks!

**Comment by DamonOehlman** [comment]
@cowboy Sounds great.  I completely missed the `async` method on my first pass so thanks for pointing me to that.  Ingenious actually, nicely done.  

With regards to IO, Rigger is completely stream based - all it's looking for is a flow of a data in and it then inspects it as the data is pushed through.  If it finds an appropriate regex pattern it does it's thing.  I added the basic file IO to make it palatable for use on it's own, although that's not the intention.

I think it will definitely be possible to use the existing Grunt IO to load the files and as per your other tasks the concat helper  will do nicely for bringing the files in initially.  Having a go at writing a grunt-rigger plugin now (but it's reasonably late here now so it will probably be finished tomorrow).  

Seriously impressed with grunt's scaffolding :)

Thanks again for all the info.

**Comment by cowboy** [comment]
Ok, keep me posted, thanks!

**Comment by DamonOehlman** [comment]
Alright, I've finished writing the first cut of the [grunt-rigger](https://github.com/DamonOehlman/grunt-rigger) plugin.  I think it's going to work out nicely, and the it behaves in a pretty similar fashion to the concat command.  I toyed with the idea of having it execute after a concat task, but in the end it made more sense for it act as a replacement in those situations where people wanted something more than a pure concat.  It supports the same src syntax for concat and the only reason that I didn't use the concat helper is that I really need to be able to provide Rigger a cwd to help it out with relative include paths.

I've started moving the build process for one of my libraries across to use grunt, and it's using the `rig` task there:

https://github.com/DamonOehlman/flip/blob/master/grunt.js#L18

There's still a bit of work to do (including test coverage) but it's a start and despite my early feelings there was nothing missing from grunt that prevented me integrating Rigger pretty simply.

Thanks to both of you for your advice - the grunt integration is going to make Rigger fit really nicely into existing build processes :)

**Comment by cowboy** [comment]
@DamonOehlman what's the point of using `reFileTask` in the task?

**Comment by DamonOehlman** [comment]
@cowboy It's a bit of a poorly named variable (I've updated it to `reFileDirective`), but the point is to detect those directives that are file related and extract the file portion of the directive.

Essentially, the way I intended rigger to work was always to consider local includes (e.g. `//= otherfile` or `//= ../parentdirfile`) relative to the file currently being processed, and as such I need to tell Rigger where the file was loaded so it can properly process those include statements. 

I chose to use a regex in the hope that other file based directives would follow the same format as existing file directives being `file_directive_name:filepath`.  If another directive was added the rigger plugin should continue to work with those directives.

Does that make sense?
